apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-east-1a

vpc:
  cidr: 172.31.0.0/16
  hostnameType: ip-name
  clusterEndpoints:
    publicAccess: false
    privateAccess: true

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    spot: true
    availabilityZones:
      - us-east-1b
    desiredCapacity: 3
    ssh:
      publicKeyName: kubernetes
